version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: dhis2_gov
    ports:
      - "5433:5432"  # HostPort:ContainerPort
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dhis_sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dhis_sync_container
    command: sh -c "python main.py && python resolve_names.py"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dhis2_gov
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - START_DATE=2024-01-01
      - END_DATE=2025-06-30
    volumes:
      - .:/app
    restart: "no"

volumes:
  postgres_data:
